CREATE TABLE TRIAL_CONTRACT (
  ID BIGINT PRIMARY KEY,
  NAME VARCHAR NOT NULL,
  TRIAL_ID BIGINT,
  FIXED_GENERAL_ITEM_SET BIGINT,
  FIXED_PERSONNEL_ITEM_SET BIGINT,
  INDIRECT_RATE DOUBLE,
  COST_PER_PARTICIPANT DOUBLE
);

CREATE TABLE TRIAL (
  ID BIGINT PRIMARY KEY,
  NAME VARCHAR NOT NULL,
  TRIAL_ARM_SET BIGINT
);

CREATE TABLE TRIAL_ARM (
  ID BIGINT PRIMARY KEY,
  NAME VARCHAR NOT NULL,
  NUM_PARTICIPANTS INT,
  VARIABLE_PROCEDURE_ITEM_SET BIGINT,
  VARIABLE_GENERAL_ITEM_SET BIGINT
);

CREATE TABLE FIXED_GENERAL_ITEM(
  ID BIGINT PRIMARY KEY,
  SPONSOR_TOTAL_PAYMENT DOUBLE
);

CREATE TABLE FIXED_PERSONNEL_ITEM(
  ID BIGINT PRIMARY KEY,
  SPONSOR_TOTAL_PAYMENT DOUBLE
);

CREATE TABLE VARIABLE_PROCEDURE_ITEM (
  ID BIGINT PRIMARY KEY,
  QUANTITY INT,
  SPONSOR_COST DOUBLE
);

CREATE TABLE VARIABLE_GENERAL_ITEM (
  ID BIGINT PRIMARY KEY,
  QUANTITY INT,
  SPONSOR_COST DOUBLE
);

CREATE TABLE JUNCTION (
  SET_ID BIGINT,
  ITEM_ID BIGINT
)
