CREATE TABLE PLACE (
  CODE VARCHAR PRIMARY KEY,
  DISPLAY VARCHAR NOT NULL
);

CREATE TABLE PATIENT (
  ADMINISTRATIVE_SEX VARCHAR,
  DATE_TIMEOF_BIRTH VARCHAR,
  ETHNIC_GROUP VARCHAR,
  PATIENT_ADDRESS VARCHAR,
  PATIENT_NAME VARCHAR,
  PHONE_NUMBER_HOME VARCHAR,
  RACE VARCHAR,
  MRN VARCHAR,
  DATE_CREATED BIGINT,
  DATE_LOCAL VARCHAR
);

-- Foreign table links.

CREATE LINKED TABLE LINK('com.microsoft.sqlserver.jdbc.SQLServerDriver', 'jdbc:sqlserver://localhost:1433;DatabaseName=test', 'admin', '12345678', '__Participant_CustomAttributesManager');
