// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package com.eztier.clickmock.infrastructure.soap.entityset


case class CreateNewEType(svcSessionToken: Option[String] = None,
  description: Option[String] = None,
  details: Option[String] = None)
      


case class CreateNewETypeResponse()
      


case class CreateNewETypeEx(svcSessionToken: Option[String] = None,
  description: Option[String] = None,
  details: Option[String] = None,
  useKeyInformation: Boolean)
      


case class CreateNewETypeExResponse()
      


case class CreateETypeForEntityType(svcSessionToken: Option[String] = None,
  entityTypeName: Option[String] = None,
  description: Option[String] = None)
      


case class CreateETypeForEntityTypeResponse()
      


case class VersionEType(svcSessionToken: Option[String] = None,
  description: Option[String] = None,
  details: Option[String] = None,
  migrateEntities: Boolean)
      


case class VersionETypeResponse()
      


case class CreateOrUpdateEType(svcSessionToken: Option[String] = None,
  description: Option[String] = None,
  details: Option[String] = None,
  migrateEntities: Boolean)
      


case class CreateOrUpdateETypeResponse(createOrUpdateETypeResult: Option[String] = None)
      


case class HasETypeNamed(svcSessionToken: Option[String] = None,
  eTypeName: Option[String] = None)
      


case class HasETypeNamedResponse(hasETypeNamedResult: Boolean)
      


case class GetETypes(svcSessionToken: Option[String] = None,
  sorted: Boolean)
      


case class GetETypesResponse(getETypesResult: Option[String] = None)
      


case class GetETypeInformationForGUI(svcSessionToken: Option[String] = None)
      


case class GetETypeInformationForGUIResponse(getETypeInformationForGUIResult: Option[String] = None)
      


case class GetSubTypeInformationForGUI(svcSessionToken: Option[String] = None,
  rootType: Option[String] = None)
      


case class GetSubTypeInformationForGUIResponse(getSubTypeInformationForGUIResult: Option[String] = None)
      


case class GetEQueryInformationForGUI(svcSessionToken: Option[String] = None)
      


case class GetEQueryInformationForGUIResponse(getEQueryInformationForGUIResult: Option[String] = None)
      


case class RenameEType(svcSessionToken: Option[String] = None,
  eTypeName: Option[String] = None,
  newETypeName: Option[String] = None)
      


case class RenameETypeResponse()
      


case class DeleteEType(svcSessionToken: Option[String] = None,
  eTypeName: Option[String] = None,
  deleteSubtypes: Boolean)
      


case class DeleteETypeResponse(deleteETypeResult: Option[String] = None)
      


case class GetNamesOfReferencedTypes(svcSessionToken: Option[String] = None,
  eTypeName: Option[String] = None)
      


case class GetNamesOfReferencedTypesResponse(getNamesOfReferencedTypesResult: Option[String] = None)
      


case class CreateEQuery(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None,
  description: Option[String] = None,
  details: Option[String] = None)
      


case class CreateEQueryResponse()
      


case class CreateParameterizedEQuery(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None,
  baseTypeName: Option[String] = None,
  paramName: Option[String] = None)
      


case class CreateParameterizedEQueryResponse()
      


case class CreateParameterizedEQueryEx(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None,
  baseTypeName: Option[String] = None,
  paramName: Option[String] = None,
  visibilityFlags: Int)
      


case class CreateParameterizedEQueryExResponse(createParameterizedEQueryExResult: Option[String] = None)
      


case class AlterEQuery(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None,
  description: Option[String] = None,
  details: Option[String] = None)
      


case class AlterEQueryResponse()
      


case class AlterEQueryEx(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None,
  description: Option[String] = None,
  details: Option[String] = None,
  replace: Boolean)
      


case class AlterEQueryExResponse()
      


case class CreateOrUpdateEQuery(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None,
  description: Option[String] = None,
  details: Option[String] = None)
      


case class CreateOrUpdateEQueryResponse()
      


case class CreateOrUpdateEQueryEx(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None,
  description: Option[String] = None,
  details: Option[String] = None,
  replace: Boolean)
      


case class CreateOrUpdateEQueryExResponse()
      


case class HasEQueryNamed(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None)
      


case class HasEQueryNamedResponse(hasEQueryNamedResult: Boolean)
      


case class GetEQueries(svcSessionToken: Option[String] = None,
  sorted: Boolean)
      


case class GetEQueriesResponse(getEQueriesResult: Option[String] = None)
      


case class AddExplicitMembers(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None,
  explicitMembers: Option[String] = None)
      


case class AddExplicitMembersResponse()
      


case class RemoveExplicitMembers(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None,
  explicitMembers: Option[String] = None)
      


case class RemoveExplicitMembersResponse()
      


case class GetExplicitMembers(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None)
      


case class GetExplicitMembersResponse(getExplicitMembersResult: Option[String] = None)
      


case class GetEQueryParameters(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None,
  sorted: Boolean)
      


case class GetEQueryParametersResponse(getEQueryParametersResult: Option[String] = None)
      


case class RenameEQuery(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None,
  newEQueryName: Option[String] = None)
      


case class RenameEQueryResponse()
      


case class DependentEQueries(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None)
      


case class DependentEQueriesResponse(dependentEQueriesResult: Option[String] = None)
      


case class DeleteEQuery(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None)
      


case class DeleteEQueryResponse(deleteEQueryResult: Option[String] = None)
      


case class EvaluateEQuery(svcSessionToken: Option[String] = None,
  eQueryXML: Option[String] = None,
  poRefsOnly: Boolean)
      


case class EvaluateEQueryResponse(evaluateEQueryResult: Option[String] = None)
      


case class EvaluateEQuerySnapshot(svcSessionToken: Option[String] = None,
  eQueryXML: Option[String] = None)
      


case class EvaluateEQuerySnapshotResponse(evaluateEQuerySnapshotResult: Option[String] = None)
      


case class GetDescription(svcSessionToken: Option[String] = None,
  eSetName: Option[String] = None)
      


case class GetDescriptionResponse(getDescriptionResult: Option[String] = None)
      


case class SetDescription(svcSessionToken: Option[String] = None,
  eSetName: Option[String] = None,
  description: Option[String] = None)
      


case class SetDescriptionResponse()
      


case class GetElements(svcSessionToken: Option[String] = None,
  eSetName: Option[String] = None)
      


case class GetElementsResponse(getElementsResult: Option[String] = None)
      


case class GetElementsSnapshot(svcSessionToken: Option[String] = None,
  eSetName: Option[String] = None)
      


case class GetElementsSnapshotResponse(getElementsSnapshotResult: Option[String] = None)
      


case class GetSharedValues(svcSessionToken: Option[String] = None,
  eTypeName: Option[String] = None)
      


case class GetSharedValuesResponse(getSharedValuesResult: Option[String] = None)
      


case class GetDetails(svcSessionToken: Option[String] = None,
  eSetName: Option[String] = None)
      


case class GetDetailsResponse(getDetailsResult: Option[String] = None)
      


case class GetDetailsReadable(svcSessionToken: Option[String] = None,
  eSetName: Option[String] = None,
  readable: Boolean)
      


case class GetDetailsReadableResponse(getDetailsReadableResult: Option[String] = None)
      


case class GetTypeCompatibleSets(svcSessionToken: Option[String] = None,
  eTypeName: Option[String] = None,
  sorted: Boolean)
      


case class GetTypeCompatibleSetsResponse(getTypeCompatibleSetsResult: Option[String] = None)
      


case class GetTypeCompatibleEQueries(svcSessionToken: Option[String] = None,
  eTypeName: Option[String] = None,
  includeParameterized: Boolean,
  sorted: Boolean)
      


case class GetTypeCompatibleEQueriesResponse(getTypeCompatibleEQueriesResult: Option[String] = None)
      


case class GetBaseTypeCompatibleEQueries(svcSessionToken: Option[String] = None,
  eTypeName: Option[String] = None,
  sorted: Boolean)
      


case class GetBaseTypeCompatibleEQueriesResponse(getBaseTypeCompatibleEQueriesResult: Option[String] = None)
      


case class GetTypeCompatibleEQueriesContaining(svcSessionToken: Option[String] = None,
  eTypeName: Option[String] = None,
  entityOid: Option[String] = None)
      


case class GetTypeCompatibleEQueriesContainingResponse(getTypeCompatibleEQueriesContainingResult: Option[String] = None)
      


case class GetESets(svcSessionToken: Option[String] = None,
  sorted: Boolean)
      


case class GetESetsResponse(getESetsResult: Option[String] = None)
      


case class EvaluateSetAlgebra(svcSessionToken: Option[String] = None,
  setAlgebra: Option[String] = None,
  binding: Option[String] = None)
      


case class EvaluateSetAlgebraResponse(evaluateSetAlgebraResult: Option[String] = None)
      


case class EvaluateSetAlgebraSnapshot(svcSessionToken: Option[String] = None,
  setAlgebra: Option[String] = None,
  binding: Option[String] = None)
      


case class EvaluateSetAlgebraSnapshotResponse(evaluateSetAlgebraSnapshotResult: Option[String] = None)
      


case class GetEQueryReferences(svcSessionToken: Option[String] = None,
  eQueryName: Option[String] = None)
      


case class GetEQueryReferencesResponse(getEQueryReferencesResult: Option[String] = None)
      


case class AddEntitySetElements(svcSessionToken: Option[String] = None,
  entitySetPORef: Option[String] = None,
  entityPORefs: Option[String] = None)
      


case class AddEntitySetElementsResponse()
      


case class RemoveEntitySetElements(svcSessionToken: Option[String] = None,
  entitySetPORef: Option[String] = None,
  entityPORefs: Option[String] = None)
      


case class RemoveEntitySetElementsResponse()
      


case class RemoveAllEntitySetElements(svcSessionToken: Option[String] = None,
  entitySetPORef: Option[String] = None)
      


case class RemoveAllEntitySetElementsResponse()
      


case class GetEntitySetElements(svcSessionToken: Option[String] = None,
  entitySetPORef: Option[String] = None,
  poRefsOnly: Boolean)
      


case class GetEntitySetElementsResponse(getEntitySetElementsResult: Option[String] = None)
      


case class GetEntitySetElementsSnapshot(svcSessionToken: Option[String] = None,
  entitySetPORef: Option[String] = None)
      


case class GetEntitySetElementsSnapshotResponse(getEntitySetElementsSnapshotResult: Option[String] = None)
      


case class SetEntitySetUniqueKeys(svcSessionToken: Option[String] = None,
  entitySetPORef: Option[String] = None,
  uniqueKeysXML: Option[String] = None)
      


case class SetEntitySetUniqueKeysResponse()
      


case class GetEntitySetUniqueKeys(svcSessionToken: Option[String] = None,
  entitySetPORef: Option[String] = None)
      


case class GetEntitySetUniqueKeysResponse(getEntitySetUniqueKeysResult: Option[String] = None)
      


case class GetEntitySetType(svcSessionToken: Option[String] = None,
  entitySetPORef: Option[String] = None)
      


case class GetEntitySetTypeResponse(getEntitySetTypeResult: Option[String] = None)
      


case class SetEntityTypeExtentUniqueKeys(svcSessionToken: Option[String] = None,
  entityTypeName: Option[String] = None,
  uniqueKeysXML: Option[String] = None)
      


case class SetEntityTypeExtentUniqueKeysResponse()
      


case class GetEntityTypeExtentUniqueKeys(svcSessionToken: Option[String] = None,
  entityTypeName: Option[String] = None)
      


case class GetEntityTypeExtentUniqueKeysResponse(getEntityTypeExtentUniqueKeysResult: Option[String] = None)
      


case class GetEntityTypeExtentUniqueKeysReadable(svcSessionToken: Option[String] = None,
  entityTypeName: Option[String] = None,
  readable: Boolean)
      


case class GetEntityTypeExtentUniqueKeysReadableResponse(getEntityTypeExtentUniqueKeysReadableResult: Option[String] = None)
      


case class UnregisterAllFromEntityTypeExtent(svcSessionToken: Option[String] = None,
  entityTypeName: Option[String] = None,
  beUnsafe: Boolean)
      


case class UnregisterAllFromEntityTypeExtentResponse()
      


case class GetStorageList()
      


case class GetStorageListResponse(GetStorageListResult: Option[com.eztier.clickmock.infrastructure.soap.entityset.ArrayOfString] = None)
      


case class ArrayOfString(string: Seq[Option[String]] = Nil)
      


case class Login(storeName: Option[String] = None,
  userName: Option[String] = None,
  password: Option[String] = None)
      


case class LoginResponse(LoginResult: Option[String] = None)
      


case class LoginAsWindowsIdentity(storeName: Option[String] = None)
      


case class LoginAsWindowsIdentityResponse(LoginAsWindowsIdentityResult: Option[String] = None)
      


case class Logoff(svcSessionToken: Option[String] = None)
      


case class LogoffResponse()
      


case class GetUserID(svcSessionToken: Option[String] = None)
      


case class GetUserIDResponse(GetUserIDResult: Option[String] = None)
      

